modLoader = "javafml"
loaderVersion = "[35,)"
license = "GPLv3"
issueTrackerURL="https://github.com/DenimRed/SimpleMuseum/issues"

[[mods]]
modId = "simplemuseum"
version = "${file.jarVersion}"
displayName = "Simple Museum"
updateJSONURL="https://raw.githubusercontent.com/DenimRed/SimpleMuseum/main/update.json"
displayURL="https://github.com/DenimRed/SimpleMuseum"
logoFile="simplemuseum.png"
credits="@jordanimating for requesting this project, @TofuToons for testing and ideas"
authors="DenimRed"
description = '''Allows you to load and display static arbitrary GeckoLib models via resource packs. Primarily useful for testing things in-game or creating displays/showcases.

Use the "Curator's Cane" (found in the "tools" creative tab) to create a dummy. Use the cane on the dummy to open its settings, or hit the dummy with the cane to remove the dummy.'''
[[dependencies.simplemuseum]]
modId="forge"
mandatory=true
versionRange="[35,)"
ordering="NONE"
side="BOTH"
[[dependencies.simplemuseum]]
modId="minecraft"
mandatory=true
versionRange="[1.16.4,1.17)"
ordering="NONE"
side = "BOTH"
[[dependencies.simplemuseum]]
modId="geckolib3"
mandatory=true
versionRange="[3,)"
ordering="AFTER"
side = "BOTH"
[[dependencies.simplemuseum]]
modId="cryptmaster"
mandatory=false
versionRange="[0.3,)"
ordering="AFTER"
side = "BOTH"
