modLoader = "javafml"
loaderVersion = "[36,)"
license = "${mod_license}"
issueTrackerURL = "${mod_url_issue}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
updateJSONURL = "${mod_url_update}"
displayURL = "${mod_url}"
logoFile = "${mod_id}.png"
credits = "${mod_credits}"
authors = "${mod_author}"
description = '''${mod_description}'''

[[dependencies."${mod_id}"]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "geckolib3"
mandatory = true
versionRange = "[3.0.15,)"
ordering = "AFTER"
side = "BOTH"
[[dependencies."${mod_id}"]]
modId = "cryptmaster"
mandatory = false
versionRange = "[0.3,)"
ordering = "AFTER"
side = "BOTH"
